### PR TITLE
Setting to log message when session cannot be found

### LINKED ISSUE #330: Do not log cleartext password on logon failure
**Describe the bug**
Full FIX message with cleartext password is logged on logon failure.

**Expected behavior**
Either do not log the FIX message, or remove cleartext password from the message.

### PR DESCRIPTION
**Pull request by fillreject**
Fixes #330 
Apologies for the delayed response. This pull request includes the changes requested here: https://github.com/quickfix-j/quickfixj/pull/340

### CODE REVIEW

File: quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java [hunk 1]
```diff
@@ -145,7 +149,16 @@ public void messageReceived(IoSession ioSession, Object message) throws Exceptio
                 }
             }
         } else {
-            log.error("Disconnecting; received message for unknown session: {}", messageString);
+            boolean logMessageWhenSessionNotFound = true;
+            if (sessionSettings.isSetting(Session.SETTING_LOG_MESSAGE_WHEN_SESSION_NOT_FOUND)) {
+                logMessageWhenSessionNotFound = sessionSettings.getBool(Session.SETTING_LOG_MESSAGE_WHEN_SESSION_NOT_FOUND);
+            }
```
Comment (chrjohn) [inline quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java:155]: Could we move this block to the constructor? The setting is not specific to any session, so we do not need to look it up on every incident.

**Review by chrjohn — CHANGES_REQUESTED** [review]
Looks good overall, thanks. Only small suggestions.

File: quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java (hunk 1 above)
Comment (fillreject) [reply quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java]: Moved the block, thanks @chrjohn

**Comment by fillreject** [comment]
Added the new setting description into configuration.html

File: quickfixj-core/src/main/doc/usermanual/usage/configuration.html [hunk 2]
```diff
@@ -601,6 +601,13 @@ <H3>QuickFIX Settings</H3>
     </TD>
     <TD> empty, ie all remote addresses are allowed </TD>
   </TR>
+  <TR ALIGN="left" VALIGN="middle">
+    <TD valign="top"> <I>LogMessageWhenSessionNotFound</I></TD>
```
Comment (chrjohn) [inline quickfixj-core/src/main/doc/usermanual/usage/configuration.html:605]: I think this should be moved to the Misc section since it is applicable to Acceptors as well as Initiators. Sorry I was not more specific when requesting this.

**Review by chrjohn — CHANGES_REQUESTED** [review]
Just one final thing. :+1: 
Thanks so far.

**Review by chrjohn — APPROVED** [review]

**Comment by lyncmi07** [comment]
Just been looking through our old tickets and found that this has been approved but not merged in.
Would it be possible to get it merged in now? (Provided its not now out of date)

**Comment by chrjohn** [comment]
Hi @lyncmi07 , I will merge this in as soon as master will be on version 3.0.0. This will be the case in the next days when 2.2.1 has been released. In the future I will create multiple branches for the different version so it can be expected that future PRs will be merged faster.
Thanks and sorry for the delay.

**Comment by lyncmi07** [comment]
Thanks for the update

File: quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java [hunk 3]
```diff
@@ -42,10 +46,17 @@
...
+    private boolean logMessageWhenSessionNotFound;
 
-    public AbstractIoHandler(NetworkingOptions options, EventHandlingStrategy eventHandlingStrategy) {
+    public AbstractIoHandler(SessionSettings settings, NetworkingOptions options, EventHandlingStrategy eventHandlingStrategy) throws FieldConvertError, ConfigError {
+        sessionSettings = settings;
         networkingOptions = options;
         this.eventHandlingStrategy = eventHandlingStrategy;
+        logMessageWhenSessionNotFound = true;
+        if (sessionSettings.isSetting(Session.SETTING_LOG_MESSAGE_WHEN_SESSION_NOT_FOUND)) {
+            logMessageWhenSessionNotFound = sessionSettings.getBool(Session.SETTING_LOG_MESSAGE_WHEN_SESSION_NOT_FOUND);
```
Comment (chrjohn) [inline quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java:58]: Sorry, one more thing: please catch and ignore `ConfigError` and `FieldConvertError` here and hence fall back to the default `logMessageWhenSessionNotFound = true` in that case. That will also make the extension of the `throws` clause (that you needed to do in various classes) unnecessary.

**Review by chrjohn — CHANGES_REQUESTED** [review]

**Comment by chrjohn** [comment]
@lyncmi07 @fillreject 
Just one more thing... ;)

File: quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java [hunk 4]
```diff
@@ -145,7 +156,11 @@ public void messageReceived(IoSession ioSession, Object message) throws Exceptio
                 }
             }
         } else {
-            log.error("Disconnecting; received message for unknown session: {}", messageString);
+            if (logMessageWhenSessionNotFound) {
+                log.error("Disconnecting; received message for unknown session: {}", messageString);
+            } else {
+                log.error("Disconnecting; received message for unknown session. remoteSessionID: {}", remoteSessionID);
```
Comment (chrjohn) [inline quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java:162]:
```suggestion
                log.error("Disconnecting; received message for unknown session. Remote SessionID: {}", remoteSessionID);
```

**Comment by fillreject** [comment]
> @lyncmi07 @fillreject
> Just one more thing... ;)
> 
> You can leave the resolution of the conflict up to me if you like...

Applied the change, thanks @chrjohn

**Comment by chrjohn** [comment]
@fillreject ,  thanks but I think you missed one thing. :)
https://github.com/quickfix-j/quickfixj/pull/352#discussion_r624789795

File: quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java (hunk 3 above)
Comment (fillreject) [reply quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java:58]: Sorry, @chrjohn, will change this, too - as requested.

Comment (chrjohn) [reply quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java:58]: No problem, thanks. :+1:

Comment (fillreject) [reply quickfixj-core/src/main/java/quickfix/mina/AbstractIoHandler.java]: @chrjohn this is done now, sorry for the delay

**Review by chrjohn — APPROVED** [review]
